### PR TITLE
Support the sources section at the bottom of the Jails view

### LINKED ISSUE #43: Support the sources section at the bottom of the Jails view
**Is your feature request related to a problem? Please describe.**
As described in the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe), we are going to create a new Jails view alongside the existing Corrections view. The bottom section of this view is a Sources section very similar to the Sources section at the bottom of the Corrections view.

**Describe the solution you'd like**
The structure and copy is identical to the sources section from the existing corrections view. The actual data sources it points to will be different but this should be supported by the existing structure of the sources component, I believe. We should just test and ensure that this is working as expected and matches the latest mocks.

**Describe alternatives you've considered**
N/A

**Additional context**
See the new "Category 2: Jails" section of [the PRD](https://docs.google.com/document/d/1eOiMzk8_eDjC4W0xn89qlkmj_6SOqi1dBTyEusAGGaI/edit?ts=5fb45edc#heading=h.s7ludzwvb7fe) and the Figma mocks it links to.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Added sources section for the new Jails view

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #43 

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Hey, @jessex, I figure out how Sources in the App works, and its require some source fields in fixture files that not exist in Jails data file. PRD says TBD for this section. So I've added support and hardcoded sources.

**Review by jessex — COMMENTED** [review]
Thanks for doing what you can so far, @nasaownsky! 

@colincadams see my screenshot below of what it looks like right now. Apparently the JAILS fixture file doesn't yet have data to support dynamic sources. Does that sound right to you, and is that planned, or is hard-coding it like this the right behavior? I also tagged @hobuobi on the PRD since the copy is still a TBD officially.

Screen Shot 2021-03-15 at 14 48 25

**Comment by colincadams** [comment]
I think hard-coding this is fine! We don't expect to expand this set of sources. 

FYI will likely end up adding some additional methodology text to this section describing how we calculate the state total metrics. This text will also be static. But we can merge this in the meantime until that is defined!

**Review by jessex — APPROVED** [review]
Merging based on @colincadams's feedback. A follow-up ticket will be filed for any further copy changes.

**Pull request merged**
