### PR TITLE
Merge 'main' into v2-jails

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

1. Merge branch 'main' into v2-jails
2. Update data files

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
This is not finished. I'll add some tests to `main` and then merge again for accordance.

**Comment by jessex** [comment]
@hobuobi wanted to check in with you and see if you're generally ready for the `v2-jails` branch to be merged into main, or if there's anything else you'd like to see happen before we do that? Once we merge it in, the app will include both corrections and jails functionality by default. So if you want any "final" changes in the corrections functionality before we merge in jails, or if you'd like for us to create an official release of the app with just the "final" corrections functionality, then we can wait. But if you're ready to merge, then we'll do it with this PR this week.

**Comment by jessex** [comment]
@nasaownsky I see that you've created a new `merge-jails` branch that you're merging into `v2-jails`. Is your plan to do this to essentially reduce the change of merge conflicts, and then in a second PR merge `v2-jails` into `main`? I'm wondering why go this route instead of just issuing a PR that merges `v2-jails` into `main` straight-away.

**Comment by nasaownsky** [comment]
@jessex I initially don't planned to merge v2-jails into main, I just wanted to pull changes from main to be sure they compatible. But if we're ready to merge jail into main I am not against.

**Comment by jessex** [comment]
@hobuobi any thought on my question for you above?

**Comment by hobuobi** [comment]
Ah, let's see -- I think it's complete enough, but we might want to keep them separate for now in case we need to send any updates to CSG as the app is being reviewed by DOC folks. @colincadams for thoughts too!

**Comment by colincadams** [comment]
@hobuobi I think this depends on whether we will want to deliver a version of the application with the annualized change (#80) without jails to CSG, or to instead deliver Jails and then the annualized data.

We can really pull off either with this merged, there just might be a bit more complex cherry-picking necessary.

**Comment by hobuobi** [comment]
Annualized change without Jails would probably be good!

**Comment by jessex** [comment]
Thanks, Humphrey and Colin! @nasaownsky do you still want to merge this PR into `v2-jails` to keep it closer to compatibility with `main` or would you rather wait and do one all-at-once handling when it's time to merge `v2-jails` into `main` itself?

**Comment by nasaownsky** [comment]
@jessex I think we can merge this PR, so it'd be less conflicts in the future.

**Review by jessex — APPROVED** [review]

**Pull request merged**
