### PR TITLE
Fixes for Jails View

### LINKED ISSUE #77: Errors when only county level jail population is present in data
**Describe the bug**

We have the calculations working for county level jail population, but when wiring up the frontend with just this information it fails to render.

**To Reproduce**
1. Checkout `v2-jails` (at 39e66e8f)
2. Replace `src/data/jails_data.json` with https://drive.google.com/file/d/1p5w9jSHHy4rZpkxVrtZk2cFVOcof8mpF/view?usp=sharing
3. Run `yarn start`

**Expected behavior**

The page should render with just the available data shown.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

Screen Shot 2021-03-23 at 12 04 01 PM

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: MacOS
 - Browser [e.g. chrome, edge]: chrome
 - Version [e.g. 22]: 39e66e8f

**Additional context**

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

1. Fixed errors when only county level jail population is present in data
2. If counties is n/a `CountySelector` would not display

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #77 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jessex** [comment]
@colincadams would you mind reviewing and testing this one? I've lost the thread on this one a bit and am not sure exactly what is being revised. Thanks!

**Review by colincadams — APPROVED** [review]
Sorry about that @nasaownsky, I should've provided the full county file in the bug! I just generated it with data for every state: https://drive.google.com/file/d/1Mg6Q0jUBTocFjMpBfSMucXdKDFl33rP6/view?usp=sharing

The error handling for not showing the county selector if we don't have that data is probably fine to stay, but we should never run into it in practice.

The rest of this looks good! Sorry, I forgot that we changed all of the charts to only show incarceration rate, so the jail population by county is totally unused. I can probably remove that from the fixture file and calculation. However this change is still useful when we only have incarceration rate by county, which will be the next data that we produce, so I think it is worth moving forward with it.

---

One additional issue I noticed when we only have incarceration rate by county, e.g. by changing the data file to just contain:
```
{"state_code":"US_CO","county_code":"US_CO_DENVER","year":"2020","month":"6","date_reported":"2020-06-30","metric":"INCARCERATION_RATE_JAIL","value":"161.3"}
{"state_code":"US_CO","county_code":"US_CO_DOUGLAS","year":"2020","month":"6","date_reported":"2020-06-30","metric":"INCARCERATION_RATE_JAIL","value":"58.7"}
{"state_code":"US_CO","county_code":"US_CO_JEFFERSON","year":"2020","month":"6","date_reported":"2020-06-30","metric":"INCARCERATION_RATE_JAIL","value":"112.7"}
```

It still shows the data for `US_CO_DENVER` as Statewide on the first chart:
Screen Shot 2021-03-25 at 12 58 06 PM

I would expect "Statewide" to be N/A in this case and to only see data on the second chart that is by county, or on the first chart if we select a county with data present, can you make that change either in this PR or separately?

**Comment by nasaownsky** [comment]
@colincadams, I fixed `Statewide` bug and update county file. Check that out!

**Comment by colincadams** [comment]
Awesome just checked and that fix looks like it is working, thanks!!

**Pull request merged**
