### PR TITLE
added no change cases

### LINKED ISSUE #52: [Corrections] Small Visual and Copy Adjustments
- Contrast for “Not Available” is not accessible — change to #8c8c8c
- “Key insights” should read “Key Insights” (capitalize the “i”)
- Numbers in the “Key Insights” captions should have commas to separate the thousands (i.e., “1,000,000” instead of “1,000”).
- When there are multiple reports in parentheses in the Sources section, there should be a comma between them. 
- If there is no previous data before the current date in the metric blocks, the percentage change should display "--%" instead of 0%. 
- Key Insights: If there is no increase/decrease, caption should say “There was no net change in [metric] during this time period.”

### PR DESCRIPTION
**Pull request by Wmaileq**
## Description of the change

- No change cases for key insights section.
- Typo fixes
- accessibility fixes

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #52.

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jessex** [comment]
@hobuobi can you take the point on testing this one? Once you've confirmed that everything you listed in the ticket is fixed on this branch, then I can do an actual _code_ review to approve this for good.

**Review by hobuobi — COMMENTED** [review]
The changes in here look right to me! 

I don't know whether this would be covered by a separate PR, but we might also want to address the inconsistencies in the metric blocks; sometimes the percent change is showing up as "0%" and others it shows up as "+0%". See below for Nebraska/NE (top) and North Dakota/ND (bottom):

Screen Shot 2021-02-12 at 12 45 50 PM

Screen Shot 2021-02-12 at 12 43 06 PM

If this is being worked on separately, feel free to ignore and merge this!

**Comment by jessex** [comment]
@Wmaileq can you fix that 0% issue that Humphrey mentioned in his review as part of this PR? We want that to always read "0%" with no plus or minus sign whenever it's going to be 0. Once that is fixed I'll merge this.

**Comment by Wmaileq** [comment]
@hobuobi @jessex This happens when the percent change is less than 0.5%. So rounded value is zero, but change is positive. Fixed

**Comment by jessex** [comment]
@hobuobi can you do one more quick test to verify the 0% change with your fixture data?

**Comment by hobuobi** [comment]
Thanks! I see the change has been made for the metric blocks, but I still see it on the graph legends (also apologies, I should have caught that in the last review):

Screen Shot 2021-02-16 at 8 49 02 AM

**Comment by jessex** [comment]
@hobuobi the legend version of that particular problem is described in #53, right? That should be fixed in the other PR, #61, if so.

**Comment by hobuobi** [comment]
Ah, very true! In that case, I think we're all good here. :)

**Review by hobuobi — APPROVED** [review]

**Review by jessex — APPROVED** [review]
Thanks, @Wmaileq!

**Pull request merged**
