### PR TITLE
Fix minor issues in tooltip

### LINKED ISSUE #55: Off-by-one error in date calculation for tooltips
Reported dates all seem to be off by -1 day, which can cross a month or even a year boundary if the actual date was the first of the month. In the example below, the date reported should be **November 30, 2020**, not November 29, 2020. 

This might actually be a data issue (assigning to @colincadams to investigate). 
Screen Shot 2021-02-08 at 3 52 00 PM

### PR DESCRIPTION
**Pull request by colincadams**
## Description of the change

For #55 there were a few underlying issues:

1. The `dateReported` is constructed with `new Date("2020-11-30")` which uses no timezone offset when constructing it. Then we printed it using the local timezone which would be "2020-11-29". 
2. We use month indices throughout (matching what appear to be javascript best practices) which means that 0 is a valid month. We were using an implicit boolean check on month instead of comparing it to null, which meant the % change part of the hint was omitted, even though it was the important part of the hint in this case.
3. Data: Maine had a few recent monthly admissions points, and then prior to that some annual admissions data. All of them were recorded as monthly, so the annual data slipped through the calculations and was treated as monthly causing the apparent 95+% decrease shown here (and is the reason for the comparison of more than a year back to the prior january).

While I was trouncing around to try to figure out what was happening I figured I would just take a stab at fixing the first two to get more familiar with what is happening in JS land. If this feels reasonable, great, if not feel free to abandon this PR and take a different approach.

I added a test for the (2), but didn't see an easy way to mock the timezone to test (1). If there is one let me know! I also fixed the data entry error for (3) separately.

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)

## Related issues

Closes #55 

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jessex** [comment]
@colincadams for testing with static times or timezones, have you looked at the `timekeeper` package? We use it in some of our other frontend projects via `import tk from "timekeeper";`

**Review by jessex — CHANGES_REQUESTED** [review]
This seems good to me! I left one comment about a way to test the time issue but let me know if that doesn't actually work.

**Comment by Wmaileq** [comment]
I've noticed tests failing in `generateHint.js` and decided to unify the date format, as we use only UTC dates.

**Review by jessex — APPROVED** [review]
The code changes look good to me here! @colincadams since you know this issue intimately, can you test and approve this if it's good to go? Also, if you do approve it, feel free to go ahead and merge. Thanks!

**Review by colincadams — COMMENTED** [review]
This looks good! The data for ME is now displaying correctly. Thanks @Wmaileq, this native Date class is a much better approach.

**Pull request merged**
