### PR TITLE
Last Updated date to each metric block tooltip.

### LINKED ISSUE #67: Add "Last Updated" date to each metric block tooltip.
We should start showing the date that we last updated the data for a given metric in the tooltips that we already provide. This should look something like what is shown below (Figma mockup https://www.figma.com/file/66HyjH0efZMoAuTlhnojWh/Justice-Counts-Report?node-id=977%3A814): 

Screen Shot 2021-03-05 at 11 26 45 AM

For now, this should use the date that the data was ingested into our database (@colincadams to provide this in the fixture file). In the future, we can move to using the actual collection date, as this will be a more accurate reflection of the freshness of the data.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Added `Last Updated` date to each metric block tooltip.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #67 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Added markup for this Issue, and while I wait from @colincadams for providing updated fixture file, I used reported dates for displaying.

**Review by jessex — COMMENTED** [review]
UI/UX looks good! Just need the data from @colincadams

**Comment by colincadams** [comment]
Uploaded the new fixture file with an additional column `date_published`
https://drive.google.com/file/d/1UUpyZMSVyJMJzgjrJnGGA3GixIamoq4y/view?usp=sharing

**Comment by nasaownsky** [comment]
@colincadams could you please also add that column to corrections file?

**Comment by colincadams** [comment]
Oops sorry about that, updated the corrections file as well now!
https://drive.google.com/file/d/1V8PfIjfsFzft0_nOmdZOZGtQGqwJm5xC/view?usp=sharing

**Review by jessex — APPROVED** [review]
Good to go! Thanks, @nasaownsky

**Pull request merged**
