### PR TITLE
Add validation/constraint for statewide incarceration rate calculation

### LINKED ISSUE #100: Add validation/constraint for statewide incarceration rate calculation
Currently, we do not place any constraint on the month over month values for the Statewide Incarceration Rate. This can result in the 
The proposed solution would be to create a floor for the % of the **population** (not % counties) represented in the calculation for any given month; data points below this floor would be omitted from the graph. The floor should be based on realistic numbers, and could be derived in a few ways (non-exhaustive): 
- 2SD below average % population represented *across* all states
- 2SD below average % population represented **in the state of interest (across all data points)**
- 2SD below average % population represented **in the state of interest, only in the given time range selected in the graph.**

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

1. Fixed counties reporting caption in graph tooltip to match #99 requirements.
2. Added arbitrary floor (10% population covered) as validation to statewide graph 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #100 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
@colincadams Check the latest changes and approve if they're right.

**Review by jessex — COMMENTED** [review]
@nasaownsky can you tell me a state where I can test this locally? For CO, it doesn't appear any of the data points are changed in the graph because none of them are below the threshold. Is there a state that you tested with?

**Comment by colincadams** [comment]
I don't think there is any fixture data that works with the 10% threshold unfortunately, but the last point for CO only covers 25% and the rest cover more so I upped the threshold to 30% to test.

before:
Screen Shot 2021-05-06 at 5 43 19 PM

after:
Screen Shot 2021-05-06 at 5 44 03 PM

It looks to me like instead of dropping the last incarceration rate point as expected, it instead just shifted the line one month to the left. I also think we will want this to affect both key insights and the charts (@hobuobi ?)

**Comment by jessex** [comment]
@colincadams would you mind taking over review for this one since you've already got a handle on it? Thanks!

**Review by colincadams — CHANGES_REQUESTED** [review]
Awesome thank you @nasaownsky! Can confirm that the shifted line issue is fixed, the chart looks great now!

I did check with @hobuobi and we want this constraint to affect the statewide incarceration rate in both key insights and the charts, sorry this wasn't super clear from the bug. It can be a little hard to tell since the rate is 139 for the two most recent months in the CO fixture data, but from the dates (or if you change a value) you can see the key insights is still showing the incarceration rate even when the coverage is too low.

I'll hold off on reviewing the code in detail for now in case this changes your implementation significantly.

**Comment by nasaownsky** [comment]
@colincadams About implementation. If, for example, latest displaying rate has constraint, all key insights should display data month back? Or just rate?

**Comment by colincadams** [comment]
@nasaownsky that is a great thought! Discussed with @hobuobi and we agree it makes sense to limit all key insights based on the percentage covered for incarceration rate. So if the constraint applies for a particular month, all statewide data for that month should be dropped.

**Comment by nasaownsky** [comment]
@colincadams Could you include `percentage_covered_population` field in `PERCENTAGE_COVERED_COUNTY` metric in jails fixture file?

**Comment by colincadams** [comment]
I can add that, and then you could limit both `INCARCERATION_RATE_JAIL` and `PERCENTAGE_COVERED_COUNTY` based on their own `percentage_covered_population` field, but you would still have to limit `POPULATION_JAIL` based on the `percentage_covered_population` of one of the other two metrics since it will have it's own value that may be different. In that case is it still useful to add the field to `PERDCENTAGE_COVERED_COUNTY`?

**Comment by nasaownsky** [comment]
@colincadams sorry for bother you, I managed to add constraint without any new data. Check this out.

**Comment by colincadams** [comment]
Not a bother at all, thanks for helping us think through the edge cases here! This seems to be working well now, and I think the approach is reasonable. Thanks for fixing the problem when percentage covered was null also!

Posting screenshots to capture the behavior change:

Screen Shot 2021-05-13 at 1 42 13 PM
Screen Shot 2021-05-13 at 1 42 51 PM

**Review by colincadams — APPROVED** [review]

**Pull request merged**
