### PR TITLE
Date range to each metric block

### LINKED ISSUE #70: Add the date range to each metric block.
Previously, the date range for the data presented in the metric blocks (both in the flow diagram and the Key Insights section) was only visible in the introductory text and the header of the flow diagram. This caused some confusion, as testers were sometimes confused about what dates the metrics were associated with. 

To fix this, we will now add the **range of dates that corresponds with a given metric** in the the metric block itself. This involves three main changes: 

1. Date range should appear below the main numbers in the metric block. This should appear as "{most recent month-year} (compared to {month-year used for the % change})" -- for example, "January 2020 (compared to January 2019)". 
2. The orange warning icon should no longer appear in the upper-right hand corner. Instead, it should appear next to the date range. 
3. The text for the warning icon tooltip should now read: "This icon indicates that the dates that correspond with this metric are not aligned with the primary date range ({most recent month-year} --> {month-year used for the % change}."

See mock below (or [Figma](https://www.figma.com/file/66HyjH0efZMoAuTlhnojWh/Justice-Counts-Report?node-id=977%3A814)): 
Date Range (Final)

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Added the date range to each metric block

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #70 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by jessex — CHANGES_REQUESTED** [review]
I think you'll need to rebase this now that I've merged your other PR against `main`, @nasaownsky. I've looked only at the most recent commit because I think the first 3 are carried over from the previous PR.

@hobuobi, I want to check in on the design here and make sure this is what we want (it may be easier for you to run this locally to see what I mean, in context, for either of these call-outs below).

For CO, the default state right now, there is one compartment in the flow diagram that has no comparison date, so the percentage change is `--` and this new warning/hint text is just a single date. Is that what you want?

Screen Shot 2021-03-17 at 13 11 59

If you open up `src/index.js` and change `US_CO` to `US_CA` to run this with CA fixture data, you'll see a mixture of different dates being displayed in the flow diagram.

screencapture-localhost-3000-2021-03-17-13_13_23

And here's one of the new tooltips:

Screen Shot 2021-03-17 at 13 17 09

So, for CA:
- The very top right of the flow diagram reads "compared to November 2019"
- The Prison Population box reads "November 2020 (compared to November 2019)"
- The two boxes with hint tooltips read "June 2019 (compared to June 2018)"
- Those hint tooltips in each case read "This icon indicates that the dates that correspond with this metric are not aligned with the primary date range (June 2018 --> November 2020)."

I admittedly don't know all of the edge cases around dates in this app yet, but I find this confusing at first glance. I am told in the top that we're comparing against November 2019 and I've got one box that shows as much (11/19 - 11/20), then I've got two boxes that have hints because they are 6/18 - 6/19, and their hint tooltips tell me the "primary date range" is 6/18 - 11/20. This is all logically _consistent_, but as a reader I am left to wonder "what is the primary date range and why are they telling me it's 6/18 - 11/20 if I've got no boxes that actually have that specific date range?"

Is this all accurate but could just be made a bit more clear? Or is there a potential data or implementation issue here? CC @colincadams

**Comment by nasaownsky** [comment]
I think that is my mistake here, @jessex, the range in tooltip must be the range for that specific metric (e.g. here June 2018 --> June 2019). This is not primary range, as I understood from issue.

**Comment by hobuobi** [comment]
Answering questions: 
- @jessex , yes, I think that default state works when there is no comparison date!
- @jessex / @nasaownsky , the range in the tooltip should be the primary range (whatever the date range at the top of the section is). So in that California example, it should read ("November 2019 → November 2020"). 

Design critiques:
- The "-->" in the tooltip should be a Unicode arrow (→). 
- The font-weight of the dates in the metric block should be medium, not bold; if we can't do a medium weight, let's just default to the normal weight instead.

**Review by jessex — APPROVED** [review]
This looks good to me now, @nasaownsky! Well done.

@hobuobi do you want to take another look or are you good to go?

**Comment by hobuobi** [comment]
A few small things upon review: 
- I noticed that the arrows seem a bit misaligned now. I don't know if this is also showing up on your end, but if it is, can we fix before merging? 
Screen Shot 2021-03-18 at 10 28 20 AM

**Comment by nasaownsky** [comment]
@jessex @hobuobi Here we go!

**Comment by jessex** [comment]
@hobuobi take a look at this on desktop and mobile and if it looks good to you, we can merge.

**Comment by hobuobi** [comment]
Nice, this looks good to me! Thank you both :)

**Pull request merged**
